name: Compiling Add-On

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Move Data Files
      run: |
        mkdir tmp
        move packs/data/adk tmp

    - name: regolith
      shell: bash
      run: winget install Bedrock-OSS.regolith

    - name: install
      run: regolith install-all

    - name: Move Data Files Back
      run: |
        move tmp/adk packs/data/adk

    - name: Compile
      run: regolith run build
