name: Compiling Add-On

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Move Data Files
      run: |
        mkdir tmp
        mv packs/data/adk tmp
        ls -R

    - name: regolith
      shell: bash
      run: |
        wget https://github.com/Bedrock-OSS/regolith/releases/download/1.0.3/regolith_1.0.3_Linux_x86_64.tar.gz
        tar -xzf regolith_1.0.3_Linux_x86_64.tar.gz
        mv regolith /usr/local/bin
        rm regolith_1.0.3_Linux_x86_64.tar.gz
        chmod +x /usr/local/bin/regolith

    - name: install
      shell: bash
      run: regolith install-all

    - name: Move Data Files Back
      run: |
        mv tmp packs/data/adk
        ls -R

    - name: Compile
      run: regolith run build
