name: Compiling Add-On

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Move Data Files
      run: |
        mkdir tmp
        mv packs/data/adk tmp

    - name: regolith
      shell: bash
      run: |
        wget https://github.com/Bedrock-OSS/regolith/releases/download/$(cat ${{ github.action_path }}/version)/regolith_$(cat ${{ github.action_path }}/version)_Linux_x86_64.tar.gz
        tar -xzf regolith_$(cat ${{ github.action_path }}/version)_Linux_x86_64.tar.gz
        mv regolith /usr/local/bin
        rm regolith_$(cat ${{ github.action_path }}/version)_Linux_x86_64.tar.gz
        chmod +x /usr/local/bin/regolith

    - name: install
      shell: bash
      run: regolith install-all

    - name: Move Data Files Back
      run: mv tmp packs/data/adk

    - name: Compile
      run: regolith run build
