name: Compiling Add-On
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Bedrock-OSS/regolith-action@v1.0.3
        with:
          profile: build
